def Y():
	print "##          ##"
	print " ##        ## "
	print "  ##      ##  "
	print "   ##    ##   "
	print "    ##  ##    "
	print "     ####     "
	print "      ##      "
	print "      ##      "
	print "      ##      "
	print "      ##      "
	print "      ##      "
def A():
	print "      ##      "
	print "     ####     "
	print "    ##  ##    "
	print "   ##    ##   "
	print "  ##      ##  "
	print " ############ "
	print " ##        ## "
	print " ##        ## "
	print " ##        ## "
	print " ##        ## "
	print " ##        ## "
print A()," ",Y()
